H_ENTRY = HttpsClient_SendSync
H_CBMCFLAGS = --unwind 1 --unwindset strlen.0:25,_flushHttpsNetworkData.0:5,_receiveHttpsMessage.0:2
H_OBJS = $(ENTRY)_harness.goto $(FREERTOS)/libraries/freertos_plus/standard/https/src/iot_https_client.goto
H_INSTFLAGS =
H_DEF =
H_INC =
H_EXPECTED = SUCCESSFUL

include ../../Makefile.common